#!/usr/bin/env python3
"""Prepare a reproducible BAF HTCondor array for the ABCD sideband skim."""

from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path


HERE = Path(__file__).resolve().parent


def arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, required=True)
    parser.add_argument("--mc-dir", type=Path, required=True)
    parser.add_argument("--submit-dir", type=Path, required=True)
    parser.add_argument("--run-label", required=True)
    parser.add_argument("--data-files-per-job", type=int, default=10)
    parser.add_argument("--mc-files-per-job", type=int, default=10)
    args = parser.parse_args()
    if args.data_files_per_job < 1 or args.mc_files_per_job < 1:
        parser.error("files-per-job values must be positive")
    if any(character.isspace() for character in args.run_label):
        parser.error("--run-label may not contain whitespace")
    return args


def root_files(directory: Path) -> list[Path]:
    if not directory.is_dir():
        raise FileNotFoundError(f"Input directory does not exist: {directory}")
    result = sorted(path.resolve() for path in directory.rglob("*.root"))
    if not result:
        raise RuntimeError(f"No ROOT files found in {directory}")
    for path in result:
        if any(character.isspace() for character in str(path)):
            raise ValueError(f"BAF manifests do not support whitespace in paths: {path}")
    return result


def chunks(values: list[Path], size: int) -> list[list[Path]]:
    return [values[index:index + size] for index in range(0, len(values), size)]


def main() -> int:
    args = arguments()
    buddy = os.environ.get("BUDDY")
    if not buddy:
        raise RuntimeError("BUDDY is not set; run this on a configured BAF login node")
    submit = args.submit_dir.expanduser().resolve()
    if str(submit).startswith(str(Path(buddy).resolve())):
        raise RuntimeError("BAF submissions must be prepared under $HOME, not under $BUDDY/CephFS")
    submit.mkdir(parents=True, exist_ok=True)
    manifests = submit / "manifests"
    manifests.mkdir(exist_ok=True)

    rows: list[tuple[str, Path, str]] = []
    counts: dict[str, tuple[int, int]] = {}
    for sample, directory, per_job in (
        ("data", args.data_dir, args.data_files_per_job),
        ("mc", args.mc_dir, args.mc_files_per_job),
    ):
        files = root_files(directory)
        groups = chunks(files, per_job)
        counts[sample] = (len(files), len(groups))
        for index, group in enumerate(groups):
            name = f"{sample}_{index:05d}.txt"
            manifest = manifests / name
            manifest.write_text("\n".join(str(path) for path in group) + "\n")
            rows.append((sample, manifest.resolve(), name))

    jobs = submit / "jobs.tsv"
    jobs.write_text("\n".join(f"{sample}\t{manifest}\t{name}" for sample, manifest, name in rows) + "\n")
    metadata = {
        "run_label": args.run_label,
        "data_directory": str(args.data_dir.expanduser().resolve()),
        "mc_directory": str(args.mc_dir.expanduser().resolve()),
        "data_files_per_job": args.data_files_per_job,
        "mc_files_per_job": args.mc_files_per_job,
        "samples": {
            sample: {"files": number_files, "jobs": number_jobs}
            for sample, (number_files, number_jobs) in counts.items()
        },
        "total_jobs": len(rows),
    }
    (submit / "submission.json").write_text(json.dumps(metadata, indent=2) + "\n")
    executable = submit / "run_closure_job.sh"
    shutil.copy2(HERE / "run_closure_job.sh", executable)
    executable.chmod(0o755)

    jdl = submit / "submit.jdl"
    jdl.write_text(f"""# Generated by prepare_submission.py. Submit from this $HOME directory.
universe              = vanilla
executable            = {executable}
arguments             = $(sample) $(manifest_name) $(ClusterId) $(ProcId) {args.run_label}

request_cpus          = 4
request_memory        = 8000 MB
request_disk          = 8192 MB
request_gpus          = 0

+ContainerOS          = \"Rocky9\"
+CephFS_IO            = \"high\"
+MaxRuntimeHours      = 2

getenv                = BUDDY
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files  = $(manifest_path)
transfer_output_files = \"\"

output                = /dev/null
error                 = /dev/null
log                   = {submit}/condor.$(ClusterId).log

queue sample,manifest_path,manifest_name from {jobs}
""")
    print(f"Prepared {len(rows)} jobs in {submit}")
    for sample, (number_files, number_jobs) in counts.items():
        print(f"  {sample}: {number_files} files in {number_jobs} jobs")
    print(f"Submit with: cd {submit} && condor_submit submit.jdl")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
